# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'E-nounce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-nounce
	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	#add pods for message kit
	pod 'MessageKit'
	pod 'InputBarAccessoryView'
  target 'E-nounceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
